### ISSUE TITLE
Balance.get () raise an error "missing required field: `payment`" despite go1.12.5

### ISSUE THREAD

**Issue by EugeneSindambiwe** [launchbadge/hedera-sdk-go#36]
Hi guys,
it seems that the bug reported by @hs011 (see below) is either back or is reproducible under other cirumstances. I am using go1.12.5 windows/amd64 and have performed go get just now.
@mehcode any idea? @hs011: Was the issue possibly resolved differently than just updating the sdk?
Thanks in avance, 
Eugene

**Comment by mehcode** [comment]
This repository is no longer being actively maintained. If you can find the issue and send a PR to address it, I'm happy to merge the fix in.

**Comment by EugeneSindambiwe** [comment]
I finally found out the reason (at least in my case): When copying the private key, I hit a button which added a character, thereby falsifying the key.
Thus, the account and the private key didn't match. The error thrown is misleading and neither related to tthe go version nor the SDK itself.
